### ISSUE TITLE
Quick save error

### ISSUE THREAD

**Issue by Lemroy** [nirewen/Quicksave#33]
When enabling Quicksave it errors and says it cannot be started.
![2019-01-18 00_20_34- shitposting - discord](https://user-images.githubusercontent.com/9974929/51321454-ee8b7e00-1ab6-11e9-9a5f-02af9ecc15ef.png)

**Comment by CompletelyUnbelievable** [comment]
It's using the deprecated version of Zerebros library which is almost certainly causing issues ([PluginUtilities](https://rauenzi.github.io/BetterDiscordAddons/docs)).

The new library can be found [here](https://github.com/rauenzi/BDPluginLibrary), quicksave will need a update so that it uses the library.

**Comment by RedCriterion** [comment]
please update the plugin <3 
i need it

**Comment by CompletelyUnbelievable** [comment]
Since pull request #34 has merged to the master branch, this issue has been solved. This issue should be closed.
